In [1]:
import pandas as pd
import numpy as np

In [3]:
dataframe = pd.read_csv('adult.test', header = None, skiprows=1)
dataframe.head()

0           1       2              3   4                    5   \
0  25     Private  226802           11th   7        Never-married   
1  38     Private   89814        HS-grad   9   Married-civ-spouse   
2  28   Local-gov  336951     Assoc-acdm  12   Married-civ-spouse   
3  44     Private  160323   Some-college  10   Married-civ-spouse   
4  18           ?  103497   Some-college  10        Never-married   

                   6           7       8        9     10  11  12  \
0   Machine-op-inspct   Own-child   Black     Male     0   0  40   
1     Farming-fishing     Husband   White     Male     0   0  50   
2     Protective-serv     Husband   White     Male     0   0  40   
3   Machine-op-inspct     Husband   Black     Male  7688   0  40   
4                   ?   Own-child   White   Female     0   0  30   

               13       14  
0   United-States   <=50K.  
1   United-States   <=50K.  
2   United-States    >50K.  
3   United-States    >50K.  
4   United-States   <=50K.

In [4]:
dataframe[14] = dataframe[14].str.rstrip('.')
dataframe.head()

0           1       2              3   4                    5   \
0  25     Private  226802           11th   7        Never-married   
1  38     Private   89814        HS-grad   9   Married-civ-spouse   
2  28   Local-gov  336951     Assoc-acdm  12   Married-civ-spouse   
3  44     Private  160323   Some-college  10   Married-civ-spouse   
4  18           ?  103497   Some-college  10        Never-married   

                   6           7       8        9     10  11  12  \
0   Machine-op-inspct   Own-child   Black     Male     0   0  40   
1     Farming-fishing     Husband   White     Male     0   0  50   
2     Protective-serv     Husband   White     Male     0   0  40   
3   Machine-op-inspct     Husband   Black     Male  7688   0  40   
4                   ?   Own-child   White   Female     0   0  30   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States    >50K  
3   United-States    >50K  
4   United-States   <=50K

In [5]:
print(dataframe[13].unique())

[' United-States' ' ?' ' Peru' ' Guatemala' ' Mexico'
 ' Dominican-Republic' ' Ireland' ' Germany' ' Philippines' ' Thailand'
 ' Haiti' ' El-Salvador' ' Puerto-Rico' ' Vietnam' ' South' ' Columbia'
 ' Japan' ' India' ' Cambodia' ' Poland' ' Laos' ' England' ' Cuba'
 ' Taiwan' ' Italy' ' Canada' ' Portugal' ' China' ' Nicaragua'
 ' Honduras' ' Iran' ' Scotland' ' Jamaica' ' Ecuador' ' Yugoslavia'
 ' Hungary' ' Hong' ' Greece' ' Trinadad&Tobago'
 ' Outlying-US(Guam-USVI-etc)' ' France']


In [5]:
object_type = dataframe.select_dtypes(include='object').columns
for col in object_type:
    dataframe[col] = dataframe[col].str.strip()

In [6]:
for col in dataframe.columns:
    print(dataframe[col].unique())

[39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' '?'
 'Self-emp-inc' 'Without-pay' 'Never-worked']
[ 77516  83311 215646 ...  34066  84661 257302]
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']
[13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' '?'
 'Protective-serv' 'Armed-Forces' 'Priv-house-serv']
['Not-in-family' 'Husband' 'Wif

In [3]:
dataframe.replace({'?' : np.nan}, inplace=True)


In [4]:
dataframe.loc[[8963]]

0    1      2        3   4        5    6              7      8       9   \
8963  90  NaN  77053  HS-grad   9  Widowed  NaN  Not-in-family  White  Female   

      10    11  12             13     14  
8963   0  4356  40  United-States  <=50K

In [5]:
dataframe.isnull().sum()

0        0
1     1836
2        0
3        0
4        0
5        0
6     1843
7        0
8        0
9        0
10       0
11       0
12       0
13     583
14       0
dtype: int64

In [6]:
for col in dataframe.columns:
    dataframe[col] = dataframe[col].fillna(dataframe[col].mode()[0])

In [ ]:
dataframe.loc[[8963]]

In [ ]:
dataframe.isnull().sum()

In [9]:
int(dataframe.duplicated(keep='first').sum())

24

In [ ]:
dataframe[dataframe.duplicated(keep=False)]

In [11]:
dataframe.drop_duplicates(inplace=True)

In [12]:
int(dataframe.duplicated().sum())

0

In [13]:
features = dataframe.drop(14, axis=1)
features

0                 1       2           3   4                   5   \
0      39         State-gov   77516   Bachelors  13       Never-married   
1      50  Self-emp-not-inc   83311   Bachelors  13  Married-civ-spouse   
2      38           Private  215646     HS-grad   9            Divorced   
3      53           Private  234721        11th   7  Married-civ-spouse   
4      28           Private  338409   Bachelors  13  Married-civ-spouse   
...    ..               ...     ...         ...  ..                 ...   
32556  27           Private  257302  Assoc-acdm  12  Married-civ-spouse   
32557  40           Private  154374     HS-grad   9  Married-civ-spouse   
32558  58           Private  151910     HS-grad   9             Widowed   
32559  22           Private  201490     HS-grad   9       Never-married   
32560  52      Self-emp-inc  287927     HS-grad   9  Married-civ-spouse   

                      6              7      8       9      10  11  12  \
0           Adm-clerical  Not-in-family  White    Male   2174   0  40   
1        Exec-managerial        Husband  White    Male      0   0  13   
2      Handlers-cleaners  Not-in-family  White    Male      0   0  40   
3      Handlers-cleaners        Husband  Black    Male      0   0  40   
4         Prof-specialty           Wife  Black  Female      0   0  40   
...                  ...            ...    ...     ...    ...  ..  ..   
32556       Tech-support           Wife  White  Female      0   0  38   
32557  Machine-op-inspct        Husband  White    Male      0   0  40   
32558       Adm-clerical      Unmarried  White  Female      0   0  40   
32559       Adm-clerical      Own-child  White    Male      0   0  20   
32560    Exec-managerial           Wife  White  Female  15024   0  40   

                  13  
0      United-States  
1      United-States  
2      United-States  
3      United-States  
4               Cuba  
...              ...  
32556  United-States  
32557  United-States  
32558  United-States  
32559  United-States  
32560  United-States  

[32537 rows x 14 columns]

In [14]:
labels = dataframe[14]
labels

0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
         ...  
32556    <=50K
32557     >50K
32558    <=50K
32559    <=50K
32560     >50K
Name: 14, Length: 32537, dtype: object

In [15]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
labels = encoder.fit_transform(labels)
labels

array([0, 0, 0, ..., 0, 0, 1])

In [3]:
print(dataframe[14].unique())

['<=50K' '>50K']
