In [11]:
import numpy as np
Y = [9, 0, 1, 4]
# Y = np.squeeze(Y)
# print(Y)
Y = np.eye(10)[Y]
print(Y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
